lorem.Lorem:
  cutoff: 5.0
  cutoff_fn: cosine_cutoff
  equivariant_message_passing: false
  initialize_node_features: false
  lr: true
  max_degree: 6
  max_degree_lr: 2
  num_features: 128
  num_message_passing: 0
  num_radial: 32
  num_species: 8
  num_spherical_features: 8
  radial_basis: basic_bernstein
